//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0

pub use super::chat::Entity as Chat;
pub use super::member::Entity as Member;
pub use super::msg::Entity as Msg;
pub use super::user::Entity as User;
