//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub sub: String,
    #[sea_orm(unique)]
    pub jti: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::msg::Entity")]
    Msg,
}

impl Related<super::msg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Msg.def()
    }
}

impl Related<super::chat::Entity> for Entity {
    fn to() -> RelationDef {
        super::member::Relation::Chat.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
